### ISSUE TITLE
那个DLL 好像起动不了, 有人知道原因嗎?

### ISSUE THREAD

**Issue by hkpeter234** [szmile2008/FTPlugin#17]
![image](https://cloud.githubusercontent.com/assets/25905432/23130705/6a4109b2-f7c2-11e6-8be7-53695bd2edf8.png)
![image](https://cloud.githubusercontent.com/assets/25905432/23130724/7b9d6fd4-f7c2-11e6-8b64-933884bea4c6.png)
![image](https://cloud.githubusercontent.com/assets/25905432/23130744/9218380c-f7c2-11e6-812b-184e94ff463c.png)
我已經打开了富途牛牛的PC 客戶端

**Comment by hkpeter234** [comment]
本人是用 64位元WIN 10
![image](https://cloud.githubusercontent.com/assets/25905432/23131424/e240cc3e-f7c4-11e6-83ea-fb2ca5ac843d.png)

**Comment by yd1231** [comment]
还原成2016-12-12版本就好了，这个新版不能打开 11111 端口

**Comment by hkpeter234** [comment]
成功了, 謝謝你

**Comment by FutunnOpen** [comment]
https://github.com/FutunnOpen/OpenQuant/issues/2 这里统一回复
